baseURL = 'https://giodi.github.io/lerntagebuch-bain/'
languageCode = 'de-ch'
title = 'Lerntagebuch zum Modul Bibliotheks- und Archivinformatik'
theme = 'nostyleplease'

[params]
  [params.theme_config]
    appearance = "auto"
    back_home_text = "Zur Startseite"
    date_format = "2006-01-02"